### PR TITLE
Added support for Turbo colormap which resolves #24

### LINKED ISSUE #24: turbo
It would be nice to include turbo https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html

### PR DESCRIPTION
**Pull request by tgalaj**
Concerns issue #24 .

### CODE REVIEW

**Comment by yuki-koyama** [comment]
Thank you for the great PR! But I have some license concerns. The original LUT seems to be licensed under Apache, so I guess there are some restrictions that should be taken into account when other software reuses it?

**Comment by tgalaj** [comment]
AFAIK there're no restrictions when using software that is licensed under Apache-2.0. This license allows doing everything with the software apart from using trademarks and logos (see this [link](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))). I agree that it needs some investigation, but unfortunately I'm not good in this legal stuff :(

**Comment by tgalaj** [comment]
I've found a little [cheat-sheet](https://choosealicense.com/licenses/apache-2.0/) for Apache 2.0.

If I understand correctly, the only thing that is required is to include a copy of Apache 2.0 license and create a short (one-liner) notice file (template is shown under the aforementioned link).

**Comment by ghutchis** [comment]
There is a Turbo LUT under MIT license here: https://github.com/cleterrier/ChrisLUTs/blob/master/Turbo.lut

**Comment by yuki-koyama** [comment]
Thank you for the pull request and the license information. 

My current understanding is that we are allowed to create a derivative work using Apache2-licensed source codes and redistribute the derivative work as a whole under MIT license (according to the 4th term of Apache2 license). But I'm still not 100% sure whether this is true and also what is the best way to incorporate the copyright and attribution notices of the Apache2-licensed original Work into this single-file Derivative Work, so I need more time for investigation.

About the license of ChrisLUTs, it says in README:

> All the LUTs in this repository except Turbo have been devised by me and are available under an MIT license.

and in my understanding, the license of the Turbo LUT is not defined in this sentence.

**Comment by bhaller** [comment]
Re: compatibility, see this: https://www.quora.com/Is-the-MIT-license-compatible-with-the-Apache-License-Version-2-APLv2

In any case, I plan to use this code in a GPL 3.0 project, and both MIT and Apache 2.0 can be used in a GPL project, so I'll be taking this PR, so thank you.

Re: this PR itself, I notice that it touches all the .png files in docs/samples/, for no apparent reason.  Probably best to remove all those diffs, apart from the addition of the Turbo PNG file.  :->

And if you want to add another project that uses tinycolormap, here's my project, which will use it soon (assuming I don't hit any roadblocks): https://github.com/MesserLab/SLiM.  Thanks!

**Pull request merged**
