### PR TITLE
Simple colormap quantization

### LINKED ISSUE #21: Non-interpolated colors
Hi, 

is there a way to get non-interpolated colors using tinycolormap to get "blocky" colors?

### PR DESCRIPTION
**Pull request by tgalaj**
This PR tries to resolve #21. 

It's extremely simple (and probably naive) colormap quantization. I used for-loops but maybe the same effect could be achieved by using some math operations.

### CODE REVIEW

**Comment by tgalaj** [comment]
I improved the previous work by replacing for loops with some math operations - it feels more robust now.

**Comment by yuki-koyama** [comment]
Hi, sorry for the late response. Could you consider the following?

1. Rename the new function with `GetQuantizedColor`
1. Rename `GetDiscreteArgument` with `QuantizeArgument` (since it does quantization, not discretization)
1. Put `GetDiscreteArgument` into the internal namespace
1. Rename `num_classes` with `num_levels` (since "class" indicates nominal scales, but the quantized colors are ordinal)
1. Remove the one that takes `std::function` as input (to take the balance between complexity and versatility)
1. Add a brief description and an example to the README

Thank you

**Comment by tgalaj** [comment]
Hi,

The requested changes are ready to be tested and merged.

Thanks!

**Comment by yuki-koyama** [comment]
Thank you very much!

**Pull request merged**
